version: '2.1'

services:
  bot:
    build:
      context: .
      dockerfile: docker/bot/Dockerfile
    volumes:
      - .:/usr/src/app
    healthcheck:
      test: ["CMD", "nc", "-z", "-w4", "bot", "3000"]
      interval: 10s
      timeout: 5s
      retries: 5
  ngrok:
    image: 68f56aa6e349
    tty: true
    ports:
      - "4047:4040"
    depends_on:
      bot:
        condition: service_healthy
    env_file: .env 
